name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Zip Release Assets
        run: |
          zip -r dist-arm64 dist-arm64
          zip -r dist-x86_64 dist-x86_64

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist-arm64.zip
            dist-x86_64.zip

      - name: Release SHAs
        run: |
          shasum -a 256 dist-arm64.zip
          shasum -a 256 dist-x86_64.zip
